apiVersion: v1
kind: ConfigMap
metadata:
  name: pipelinepulse-config
  namespace: pipelinepulse
data:
  # General
  ENVIRONMENT: "production"
  
  # Backend Settings
  JWT_EXPIRE_MINUTES: "1440"
  CORS_ORIGINS: "[\"https://pipelinepulse.example.com\"]"
  
  # Airflow Core settings
  AIRFLOW__CORE__EXECUTOR: "KubernetesExecutor"
  AIRFLOW__CORE__SQL_ALCHEMY_CONN: "postgresql+psycopg2://postgres:postgres@postgres-service.pipelinepulse.svc.cluster.local:5432/pipelinepulse"
  AIRFLOW__CORE__DAGS_ARE_PAUSED_AT_CREATION: "true"
  AIRFLOW__CORE__LOAD_EXAMPLES: "false"
  AIRFLOW__LOGGING__BASE_LOG_FOLDER: "/opt/airflow/logs"
  
  # Frontend Configs
  NEXT_PUBLIC_API_URL: "https://api.pipelinepulse.example.com"
  NEXT_PUBLIC_WS_URL: "wss://api.pipelinepulse.example.com"
